export const countries = [
    {primary: 'Afghanistan', shortName: 'AF',id:"1"}, 
  {primary: 'Åland Islands', shortName: 'AX',id:"2"}, 
  {primary: 'Albania', shortName: 'AL',id:"3"}, 
  {primary: 'Algeria', shortName: 'DZ',id:"4"}, 
  {primary: 'American Samoa', shortName: 'AS',id:"5"}, 
  {primary: 'AndorrA', shortName: 'AD',id:"6"}, 
  {primary: 'Angola', shortName: 'AO',id:"7"}, 
  {primary: 'Anguilla', shortName: 'AI',id:"8"}, 
  {primary: 'Antarctica', shortName: 'AQ',id:"9"}, 
  {primary: 'Antigua and Barbuda', shortName: 'AG',id:"10"}, 
  {primary: 'Argentina', shortName: 'AR',id:"11"}, 
  {primary: 'Armenia', shortName: 'AM',id:"12"}, 
  {primary: 'Aruba', shortName: 'AW',id:"13"}, 
  {primary: 'Australia', shortName: 'AU',id:"14"}, 
  {primary: 'Austria', shortName: 'AT',id:"15"}, 
  {primary: 'Azerbaijan', shortName: 'AZ',id:"16"}, 
  {primary: 'Bahamas', shortName: 'BS',id:"17"}, 
  {primary: 'Bahrain', shortName: 'BH',id:"18"}, 
  {primary: 'Bangladesh', shortName: 'BD',id:"19"}, 
  {primary: 'Barbados', shortName: 'BB',id:"20"}, 
  {primary: 'Belarus', shortName: 'BY',id:"21"}, 
  {primary: 'Belgium', shortName: 'BE',id:"22"}, 
  {primary: 'Belize', shortName: 'BZ',id:"23"}, 
  {primary: 'Benin', shortName: 'BJ',id:"24"}, 
  {primary: 'Bermuda', shortName: 'BM',id:"25"}, 
  {primary: 'Bhutan', shortName: 'BT',id:"26"}, 
  {primary: 'Bolivia', shortName: 'BO',id:"27"}, 
  {primary: 'Bosnia and Herzegovina', shortName: 'BA',id:"28"}, 
  {primary: 'Botswana', shortName: 'BW',id:"29"}, 
  {primary: 'Bouvet Island', shortName: 'BV',id:"30"}, 
  {primary: 'Brazil', shortName: 'BR',id:"31"}, 
  {primary: 'British Indian Ocean Territory', shortName: 'IO',id:"32"}, 
  {primary: 'Brunei Darussalam', shortName: 'BN',id:"33"}, 
  {primary: 'Bulgaria', shortName: 'BG',id:"34"}, 
  {primary: 'Burkina Faso', shortName: 'BF',id:"35"}, 
  {primary: 'Burundi', shortName: 'BI',id:"36"}, 
  {primary: 'Cambodia', shortName: 'KH',id:"37"}, 
  {primary: 'Cameroon', shortName: 'CM',id:"38"}, 
  {primary: 'Canada', shortName: 'CA',id:"39"}, 
  {primary: 'Cape Verde', shortName: 'CV',id:"40"}, 
  {primary: 'Cayman Islands', shortName: 'KY',id:"41"}, 
  {primary: 'Central African Republic', shortName: 'CF',id:"42"}, 
  {primary: 'Chad', shortName: 'TD',id:"43"}, 
  {primary: 'Chile', shortName: 'CL',id:"44"}, 
  {primary: 'China', shortName: 'CN',id:"45"}, 
  {primary: 'Christmas Island', shortName: 'CX',id:"46"}, 
  {primary: 'Cocos (Keeling) Islands', shortName: 'CC',id:"47"}, 
  {primary: 'Colombia', shortName: 'CO',id:"48"}, 
  {primary: 'Comoros', shortName: 'KM',id:"49"}, 
  {primary: 'Congo', shortName: 'CG',id:"50"}, 
  {primary: 'Congo, The Democratic Republic of the', shortName: 'CD',id:"51"}, 
  {primary: 'Cook Islands', shortName: 'CK',id:"52"}, 
  {primary: 'Costa Rica', shortName: 'CR',id:"53"}, 
  {primary: 'Cote D\'Ivoire', shortName: 'CI',id:"54"}, 
  {primary: 'Croatia', shortName: 'HR',id:"55"}, 
  {primary: 'Cuba', shortName: 'CU',id:"56"}, 
  {primary: 'Cyprus', shortName: 'CY',id:"57"}, 
  {primary: 'Czech Republic', shortName: 'CZ',id:"58"}, 
  {primary: 'Denmark', shortName: 'DK',id:"59"}, 
  {primary: 'Djibouti', shortName: 'DJ',id:"60"}, 
  {primary: 'Dominica', shortName: 'DM',id:"61"}, 
  {primary: 'Dominican Republic', shortName: 'DO',id:"62"}, 
  {primary: 'Ecuador', shortName: 'EC',id:"63"}, 
  {primary: 'Egypt', shortName: 'EG',id:"64"}, 
  {primary: 'El Salvador', shortName: 'SV',id:"65"}, 
  {primary: 'Equatorial Guinea', shortName: 'GQ',id:"66"}, 
  {primary: 'Eritrea', shortName: 'ER',id:"67"}, 
  {primary: 'Estonia', shortName: 'EE',id:"68"}, 
]